user_1:
  assets:
    - BTC
    - ETH
  amount_usd:
    BTC: 50
    ETH: 50
  drop_percent: 0.10
  frequency: monthly
  email_to: example1@example.com
  email_from: example2@example.com
  azure_vault:
    name: my-key-vault
    url: https://my-key-vault.vault.azure.net/
